### ISSUE TITLE
Add pylint to sniff for PEP8 compliance

### ISSUE THREAD

**Issue by ArtPoon** [PoonLab/covizu#507]
Add as a GitHub action

**Comment by GopiGugan** [comment]
1. Go to "Actions" tab
2. Search for pylint 
3. Click on configure
4. Add the following yaml:
```yaml
name: Pylint check

on:
  pull_request:
    branches:
      - "master"
      - "dev"

jobs:
  pylint-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Create virtual environment
      run: python -m venv venv
      working-directory: ${{ github.workspace }}

    - name: Activate virtual environment and install dependencies
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        deactivate
      working-directory: ${{ github.workspace }}

    - name: Analyze code with Pylint
      run: |
        source venv/bin/activate
        pylint $(git ls-files '*.py')
        deactivate
      working-directory: ${{ github.workspace }}
```

I've attached the list of warnings that pylint is currently throwing. We should resolve these before setting this Github Action or else our pull requests will fail
[pylint_report.log](https://github.com/PoonLab/covizu/files/14496057/pylint_report.log)
